[project]
name = "healthtech"
version = "0.1.0"
description = "API RESTful desenvolvida com FastAPI que consolida IBGE, DataSUS, taxas Banco Central do Brasil e métricas de densidade."
readme = "README.md"
authors = [
    { name = "Área 41", email = "" }
]
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.3",
    "cachetools>=7.2.0",
    "fastapi>=0.142.1",
    "httpx>=0.28.1",
    "plotly>=7.1.0",
    "python-dotenv>=1.2.3",
    "scalar-fastapi>=1.9.1",
    "streamlit>=1.64.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
healthtech = "healthtech:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
